esphome:
 name: energymonitor
 friendly_name: EnergyMonitor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "C95l8q44KFaRHqi7Gc97FYUBCnVtIBw821nMbWtBvmE="

ota:
  - platform: esphome
    password: "c107ae6b5ea56e3dbc6ca03e404627db"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Energymonitor Fallback Hotspot"
    password: "McTDOvNa3362"

web_server:
  port: 80

light:
  - platform: neopixelbus
    id: energymonitor
    type: GRB
    variant: LC8812
    pin: GPIO2
    num_leds: 18
    color_correct: [75%, 75%, 75%]
    name: "Energy Monitor"

  - platform: partition
    name: "Now"
    segments:
      - id: energymonitor
        from: 0
        to: 2

  - platform: partition
    name: "P1_1"
    segments:
      - id: energymonitor
        from: 3
        to: 3

  - platform: partition
    name: "P1_2"
    segments:
      - id: energymonitor
        from: 4
        to: 4

  - platform: partition
    name: "P1_3"
    segments:
      - id: energymonitor
        from: 5
        to: 5

  - platform: partition
    name: "P1_4"
    segments:
      - id: energymonitor
        from: 6
        to: 6

  - platform: partition
    name: "P1_5"
    segments:
      - id: energymonitor
        from: 7
        to: 7

  - platform: partition
    name: "P1_6"
    segments:
      - id: energymonitor
        from: 8
        to: 8

  - platform: partition
    name: "P1_7"
    segments:
      - id: energymonitor
        from: 9
        to: 9

  - platform: partition
    name: "P1_8"
    segments:
      - id: energymonitor
        from: 10
        to: 10

  - platform: partition
    name: "P1_9"
    segments:
      - id: energymonitor
        from: 11
        to: 11

  - platform: partition
    name: "P1_10"
    segments:
      - id: energymonitor
        from: 12
        to: 12

  - platform: partition
    name: "P1_11"
    segments:
      - id: energymonitor
        from: 13
        to: 13

  - platform: partition
    name: "P1_12"
    segments:
      - id: energymonitor
        from: 14
        to: 14

  - platform: partition
    name: "Next"
    segments:
      - id: energymonitor
        from: 15
        to: 17
