esphome:
  name: energymonitor
  friendly_name: EnergyMonitor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YourKeyHere"

ota:
  - platform: esphome
    password: "YourPaaswordHere"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Energymonitor Fallback Hotspot"
    password: "McTDOvNa3362"

web_server:
  port: 80

light:
  - platform: neopixelbus
    id: energymonitor
    type: GRB
    variant: LC8812
    pin: GPIO2
    num_leds: 18
    name: "Energy Monitor"

  - platform: partition
    name: "Now"
    segments:
      - id: energymonitor
        from: 0
        to: 5


  - platform: partition
    name: "P1"
    segments:
      - id: energymonitor
        from: 6
        to: 8

  - platform: partition
    name: "Batt"
    segments:
      - id: energymonitor
        from: 9
        to: 11

  - platform: partition
    name: "Next"
    segments:
      - id: energymonitor
        from: 12
        to: 17
            
