#### Energieprijs ####
- platform: template
  sensors:
    energie_prijs:
      friendly_name: Energie Prijs
      value_template: "{% if states ('sensor.dagprijs_current_electricity_market_price') | float < '0'|float %}
      Terugleveren
      {% elif states ('sensor.dagprijs_current_electricity_market_price') | float|round(2) == '0'|float %}
      Gratis
      {% elif states ('sensor.dagprijs_current_electricity_market_price') | float < states ('sensor.dagprijs_average_electricity_price_today') | float  %}
      Goedkoop
      {% elif states ('sensor.dagprijs_current_electricity_market_price') | float|round(2) == states ('sensor.dagprijs_average_electricity_price_today') | float|round(2) %}
      Gemiddeld
      {% else %}
      Duur
      {% endif %}"

